create or replace PACKAGE GLOBAL_EXCEPTIONS AS 
   /*The following exception will be executed when a technician
   that does not exist is called from the procedure chercher_tests_faits_par_tech*/
   TECH_NOT_FOUND EXCEPTION;
   PRAGMA EXCEPTION_INIT(TECH_NOT_FOUND, -20104);
   
   SAMPLE_NOT_FOUND EXCEPTION;
   PRAGMA EXCEPTION_INIT(SAMPLE_NOT_FOUND, -20101);
   
   TEST_NOT_FOUND EXCEPTION;
   PRAGMA EXCEPTION_INIT(TEST_NOT_FOUND, -20102);
   
   NOT_TEST_FOR_SAMPLE EXCEPTION;
   PRAGMA EXCEPTION_INIT(NOT_TEST_FOR_SAMPLE, -20103);
   
   RESULT_NOT_FOUND EXCEPTION;
   PRAGMA EXCEPTION_INIT(RESULT_NOT_FOUND, -20001);
   

END GLOBAL_EXCEPTIONS;